// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	ActionSubmissionPublishOperation         OperationName = "ActionSubmissionPublish"
	ActionSubmissionRejectOperation          OperationName = "ActionSubmissionReject"
	ActionSubmissionRequestChangesOperation  OperationName = "ActionSubmissionRequestChanges"
	ActionSubmissionRevokeOperation          OperationName = "ActionSubmissionRevoke"
	ActionSubmissionSubmitOperation          OperationName = "ActionSubmissionSubmit"
	ActionSubmissionTriggerPublishOperation  OperationName = "ActionSubmissionTriggerPublish"
	ActionSubmissionTriggerValidateOperation OperationName = "ActionSubmissionTriggerValidate"
	ActionSubmissionValidateOperation        OperationName = "ActionSubmissionValidate"
	CreateSubmissionOperation                OperationName = "CreateSubmission"
	GetSubmissionOperation                   OperationName = "GetSubmission"
	ListSubmissionsOperation                 OperationName = "ListSubmissions"
	PatchSubmissionCompletedOperation        OperationName = "PatchSubmissionCompleted"
	PatchSubmissionModelOperation            OperationName = "PatchSubmissionModel"
)
