/*
 * StrafesNET Submissions - OpenAPI 3.1
 *
 * Browse and manage map submissions in the staging pipeline.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Id {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
}

impl Id {
    pub fn new() -> Id {
        Id {
            id: None,
        }
    }
}

