/*
 * StrafesNET Submissions - OpenAPI 3.1
 *
 * Browse and manage map submissions in the staging pipeline.
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub id: Option<i64>,
    #[serde(rename = "Username", skip_serializing_if = "Option::is_none")]
    pub username: Option<String>,
    #[serde(rename = "StateID", skip_serializing_if = "Option::is_none")]
    pub state_id: Option<i32>,
}

impl User {
    pub fn new() -> User {
        User {
            id: None,
            username: None,
            state_id: None,
        }
    }
}

