// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetUser implements getUser operation.
//
// Retrieve user with ID.
//
// GET /users/{UserID}
func (UnimplementedHandler) GetUser(ctx context.Context, params GetUserParams) (r *User, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUserRank implements getUserRank operation.
//
// Retrieve rank of user.
//
// GET /users/{UserID}/rank
func (UnimplementedHandler) GetUserRank(ctx context.Context, params GetUserRankParams) (r *Rank, _ error) {
	return r, ht.ErrNotImplemented
}

// ListRanks implements listRanks operation.
//
// Get list of ranks.
//
// GET /ranks
func (UnimplementedHandler) ListRanks(ctx context.Context, params ListRanksParams) (r []Rank, _ error) {
	return r, ht.ErrNotImplemented
}

// ListTimes implements listTimes operation.
//
// Get list of times.
//
// GET /times
func (UnimplementedHandler) ListTimes(ctx context.Context, params ListTimesParams) (r []Time, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
