FROM oven/bun:latest

WORKDIR /app

COPY eslint.config.mjs ./
COPY next.config.ts ./
COPY tsconfig.json ./
COPY package.json ./
COPY src ./

EXPOSE 3000/tcp

ENV NEXT_TELEMETRY_DISABLED=1

RUN bun install
RUN bun run build
ENTRYPOINT ["bun", "run", "start"]